// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo3yh1lUOtUwCK7Vx9jT_8S3scxuyYhKQ',
    appId: '1:474424103318:web:a059764a4ca0b42d07cdb7',
    messagingSenderId: '474424103318',
    projectId: 'city-weather-travel',
    authDomain: 'city-weather-travel.firebaseapp.com',
    storageBucket: 'city-weather-travel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_N_eN2AQ2Q6WoWAiP_emrUpmXmUY_jI',
    appId: '1:474424103318:android:ca429b7239d994d607cdb7',
    messagingSenderId: '474424103318',
    projectId: 'city-weather-travel',
    storageBucket: 'city-weather-travel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGKLnedG5opv6XPh70tXtOCbh9iq1t6S0',
    appId: '1:474424103318:ios:265a7851de42880107cdb7',
    messagingSenderId: '474424103318',
    projectId: 'city-weather-travel',
    storageBucket: 'city-weather-travel.appspot.com',
    iosBundleId: 'com.example.listApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGKLnedG5opv6XPh70tXtOCbh9iq1t6S0',
    appId: '1:474424103318:ios:5f5ab0e0ab4fd79f07cdb7',
    messagingSenderId: '474424103318',
    projectId: 'city-weather-travel',
    storageBucket: 'city-weather-travel.appspot.com',
    iosBundleId: 'com.example.listApi.RunnerTests',
  );
}
